### PR TITLE
answers can now be reported

### PR DESCRIPTION
**Pull request by kyelindholm**
Now when you click on 'Report' in an answer, the text will change from 'Report' to 'Reported', it'll no longer be clickable, and the next time the QuestionList is rendered that answer won't show up.

### CODE REVIEW

**Review by ks10825n — APPROVED** [review]
Look good! I couldn't find anything to comment on so I tried to break it lol. I fetched your code and pulled down locally. After you report the answers are they meant to disappear from the view?

**Comment by kyelindholm** [comment]
> Look good! I couldn't find anything to comment on so I tried to break it lol. I fetched your code and pulled down locally. After you report the answers are they meant to disappear from the view?

Thanks! Not until the page is re-rendered otherwise. I thought so too initially, but that would prevent the 'Report' -> 'Reported' text change.

**Comment by ks10825n** [comment]
Ah got it. I was thinking the GET request shouldn't ignore reported answers from a UI perspective since you can just spam report everything like I did haha. But either way, this looks good to merge!

**Comment by kyelindholm** [comment]
> Ah got it. I was thinking the GET request shouldn't ignore reported answers from a UI perspective since you can just spam report everything like I did haha. But either way, this looks good to merge!

Haha yeah, maybe not the best implementation, but that they gave us in the server.

**Pull request merged**
